mutate_chance:
  primary_data.family: 0.4
  primary_data.genus: 0.7
  primary_data.species: 0.8

mutation_rate:
  primary_data.family: 0.3
  primary_data.genus: 0.4
  primary_data.species: 0.4

growth_bias:
  primary_data.family: 0.1
  primary_data.genus: 0.2
  primary_data.species: 0.3

noise_std:
  primary_data.family: 0.05
  primary_data.genus: 0.05
  primary_data.species: 0.05