# Step 1:
primary_data:
  woodType:
    - [Softwood, Hardwood]
    #- Softwood
    #- Hardwood
  sourceNo:
    #- [DS01, DS04, DS07, DS11]
    - [DS04, DS11]
    - DS07
    - DS01


  family:
    #- [Pinaceae, Fagaceae,]
    #- ['Annonaceae', 'Ephedraceae', 'Fabaceae', 'Lauraceae']
    - None

  genus:
    - [Pinus, Picea, Abies, Larix, Tsuga, Cedrus, Juniperus, Taxus, Cupressus]
    - [Quercus, Fagus, Castanea, Nothofagus, Tilia, Ulmus, Acer, Fraxinus]
    - [Pinus, Picea, Abies, Nothofagus, Eucalyptus, Acacia, Araucaria, Podocarpus]
    - [Alnus, Betula, Populus, Salix, Carpinus, Corylus, Juglans]
    - [Quercus, Pinus, Juniperus, Cedrus, Cupressus, Olea, Pistacia]
    - [Phoebe, Shorea, Dipterocarpus, Hopea, Terminalia, Albizia, Dalbergia]
    - [Alnus, Betula, Populus, Salix, Eucalyptus, Ailanthus, Robinia]
    - [Pinus, Quercus, Fagus, Betula, Abies, Picea, Tilia, Ulmus, Acer]
    - [Picea, Abies, Larix, Betula, Salix, Alnus, Populus]
    - [Quercus, Juglans, Dalbergia, Tectona, Swietenia, Pinus, Pterocarpus, Cedrela]

    #- [None]
  
  species:
    #- [PinusSylvestris, PiceaAbies, AbiesAlba]
    #- [LarixDecidua, TsugaHeterophylla, CedrusAtlantica]
    #- [LarixDecidua, TsugaHeterophylla, PiceaAbies]
    #- [QuercusRobur, FagusSylvatica, CastaneaSativa, NothofagusObliqua]
    #- [AlnusFirma]
    - [None]

  view:
    - TS # Cross Section
    #- RLS # Radial Longitudinal Section
    #- TLS # Tangential Longitudinal Section

  lens:
    - [10, 25]
    - [None]

  maxShots:
    #- 1000
    - 500

  noShotsRange:
    #- [[2, 10], [12, 17]]
    #- [[34, 60]]
    - None

  filterNo:
    - FF01
    - FF02
    #- FF03
    #- None

secondaryDataBins:
  - SD01


# Step 2:
preProcessingNo:
  - PPO1
  - PP02
  #- PP03

featureBins:
  - FB01
  #- FB02
  #- FB03

# Step 3:

metricModelNo:
  - MM01
  #- MM02

