branch_linear_01:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 1.000 * gen / 50))'
  control_branches:
  - branch_linear_01_A
  - branch_linear_01_B
  - branch_linear_01_C
  - branch_linear_01_D
  - branch_linear_01_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: &id001
    include:
      primary_data.sourceNo:
      - DS01
      - DS04
      primary_data.woodType:
      - Softwood
    exclude:
      primary_data.genus:
      - Quercus
      - Eucalyptus
branch_linear_02:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 2.000 * gen / 50))'
  control_branches:
  - branch_linear_02_A
  - branch_linear_02_B
  - branch_linear_02_C
  - branch_linear_02_D
  - branch_linear_02_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_linear_03:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 3.000 * gen / 50))'
  control_branches:
  - branch_linear_03_A
  - branch_linear_03_B
  - branch_linear_03_C
  - branch_linear_03_D
  - branch_linear_03_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_linear_04:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 4.000 * gen / 50))'
  control_branches:
  - branch_linear_04_A
  - branch_linear_04_B
  - branch_linear_04_C
  - branch_linear_04_D
  - branch_linear_04_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_linear_05:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 5.000 * gen / 50))'
  control_branches:
  - branch_linear_05_A
  - branch_linear_05_B
  - branch_linear_05_C
  - branch_linear_05_D
  - branch_linear_05_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_inverse_01:
  mutation_strategy: inverse
  mutation_func: 'lambda gen: max(0.05, min(0.45, 1.000 / (gen + 1)))'
  control_branches:
  - branch_inverse_01_A
  - branch_inverse_01_B
  - branch_inverse_01_C
  - branch_inverse_01_D
  - branch_inverse_01_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_inverse_02:
  mutation_strategy: inverse
  mutation_func: 'lambda gen: max(0.05, min(0.45, 2.000 / (gen + 1)))'
  control_branches:
  - branch_inverse_02_A
  - branch_inverse_02_B
  - branch_inverse_02_C
  - branch_inverse_02_D
  - branch_inverse_02_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_inverse_03:
  mutation_strategy: inverse
  mutation_func: 'lambda gen: max(0.05, min(0.45, 3.000 / (gen + 1)))'
  control_branches:
  - branch_inverse_03_A
  - branch_inverse_03_B
  - branch_inverse_03_C
  - branch_inverse_03_D
  - branch_inverse_03_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_inverse_04:
  mutation_strategy: inverse
  mutation_func: 'lambda gen: max(0.05, min(0.45, 4.000 / (gen + 1)))'
  control_branches:
  - branch_inverse_04_A
  - branch_inverse_04_B
  - branch_inverse_04_C
  - branch_inverse_04_D
  - branch_inverse_04_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_inverse_05:
  mutation_strategy: inverse
  mutation_func: 'lambda gen: max(0.05, min(0.45, 5.000 / (gen + 1)))'
  control_branches:
  - branch_inverse_05_A
  - branch_inverse_05_B
  - branch_inverse_05_C
  - branch_inverse_05_D
  - branch_inverse_05_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_random_01:
  mutation_strategy: random
  mutation_func: 'lambda gen: random.uniform(0.05, 0.45)'
  control_branches:
  - branch_random_01_A
  - branch_random_01_B
  - branch_random_01_C
  - branch_random_01_D
  - branch_random_01_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_random_02:
  mutation_strategy: random
  mutation_func: 'lambda gen: random.uniform(0.05, 0.45)'
  control_branches:
  - branch_random_02_A
  - branch_random_02_B
  - branch_random_02_C
  - branch_random_02_D
  - branch_random_02_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_random_03:
  mutation_strategy: random
  mutation_func: 'lambda gen: random.uniform(0.05, 0.45)'
  control_branches:
  - branch_random_03_A
  - branch_random_03_B
  - branch_random_03_C
  - branch_random_03_D
  - branch_random_03_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_random_04:
  mutation_strategy: random
  mutation_func: 'lambda gen: random.uniform(0.05, 0.45)'
  control_branches:
  - branch_random_04_A
  - branch_random_04_B
  - branch_random_04_C
  - branch_random_04_D
  - branch_random_04_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_random_05:
  mutation_strategy: random
  mutation_func: 'lambda gen: random.uniform(0.05, 0.45)'
  control_branches:
  - branch_random_05_A
  - branch_random_05_B
  - branch_random_05_C
  - branch_random_05_D
  - branch_random_05_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_constant_01:
  mutation_strategy: constant
  mutation_func: 'lambda gen: 0.050'
  control_branches:
  - branch_constant_01_A
  - branch_constant_01_B
  - branch_constant_01_C
  - branch_constant_01_D
  - branch_constant_01_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_constant_02:
  mutation_strategy: constant
  mutation_func: 'lambda gen: 0.150'
  control_branches:
  - branch_constant_02_A
  - branch_constant_02_B
  - branch_constant_02_C
  - branch_constant_02_D
  - branch_constant_02_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_constant_03:
  mutation_strategy: constant
  mutation_func: 'lambda gen: 0.250'
  control_branches:
  - branch_constant_03_A
  - branch_constant_03_B
  - branch_constant_03_C
  - branch_constant_03_D
  - branch_constant_03_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_constant_04:
  mutation_strategy: constant
  mutation_func: 'lambda gen: 0.350'
  control_branches:
  - branch_constant_04_A
  - branch_constant_04_B
  - branch_constant_04_C
  - branch_constant_04_D
  - branch_constant_04_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
branch_constant_05:
  mutation_strategy: constant
  mutation_func: 'lambda gen: 0.450'
  control_branches:
  - branch_constant_05_A
  - branch_constant_05_B
  - branch_constant_05_C
  - branch_constant_05_D
  - branch_constant_05_E
  allow_multi_mutation: true
  fallback_on_invalid: true
  corridor: 0.1
  max_generations: 50
  generation_size: 30
  elite_size: 5
  constraints: *id001
