branch_linear_01:
  mutation_strategy: linear
  mutation_func: 'lambda gen: max(0.05, min(0.45, 1.000 * gen / 50))'
  control_branches:
    - branch_linear_01_A
    - branch_linear_01_B
  allow_multi_mutation: true
  fallback_on_invalid: true
  max_generations: 50
  generation_size: 30
  elite_size: 5
  static_mutate_params:
    primary_data.sourceNo:
      mutate_chance: 0.2
      mutation_rate: 0.3
      must_contain: ["DS01", "DS04"]
    primary_data.woodType:
      mutate_chance: 0.2
      must_contain: ["Softwood"]
  dependent_mutate_params:
    primary_data.genus:
      mutate_chance: 0.1
      #must_not_contain: ["Quercus", "Eucalyptus"]
      must_contain: [null]

