DoE_UUID: "{DoE_UUID}"

primary_data:
  sourceNo: "{sourceNo}"
  woodType: "{woodType}"
  family: "{family}"
  genus: "{genus}"
  species: "{species}"
  view: "{view}"
  lens: "{lens}"
  maxShots: "{maxShots}"
  noShotsRange: "{noShotsRange}"

secondary_data:
  secondaryDataBins: "{secondaryDataBins}"

modelling:
  metricModelNo: "{metricModelNo}"

preprocessing:
  preProcessingNo: "{preProcessingNo}"  

modeling:
  metricModelNo: "{metricModelNo}"        
