

tasks:
  #TA01_Setup:
  #  TA01_A_CreateDatabases:
  #    taskName: TA01_A_CreateDatabases
  #    prd_db: "prd"
  #    source_db: "source"
  #    raw_db: "raw"


  TA11_DataImport:
    TA11_0_DataImportWrapper:
      taskName: TA11_0_DataImportWrapper
      possible_subTasks:
        - TA11_A_Import_DS01
        - TA11_B_Import_DS04
        - TA11_C_Import_DS07
        - TA11_D_Import_DS11
        - TA11_E_Import_SecondaryData

    TA11_A_Import_DS01:
      TaskName : "TA11_A_Import_DS01"
      sourceFile_path : "data/sourceData/primary/DS01"
      sourceFile_path_debug : "data/sourceData/primary/DS01"
      destFile_path : "data/rawData/primary/DS01.hdf5"
      DS_Name : "DS01"
      citeKey : "dasilva_2017"
      batch_size : 10
      sourceNo : "DS01"


    TA11_B_Import_DS04:
      TaskName : "TA11_B_Import_DS04"
      sourceFile_path : "data/sourceData/primary/DS04/DS04.h5"
      sourceFile_path_debug : "data/sourceData/primary/DS04"
      destFile_path : "data/rawData/primary/DS04.hdf5"
      DS_Name : "DS04"
      citeKey : "sugiyama_2020"
      chunk_size : 512
      sourceNo : "DS04"
      progress_update_cylce : 5
      
      
    TA11_C_Import_DS07:
      TaskName: "TA11_C_Import_DS07"
      sourceFile_path: "data/sourceData/primary/DS07"
      sourceFile_path_debug: "data/sourceData/primary/DS07"
      destFile_path: "data/rawData/primary/DS07.hdf5"
      DS_Name: "DS07"
      citeKey: "martins_2012"
      batch_size: 10
      sourceNo: "DS07"
      progress_update_cylce : 5

    TA11_D_Import_DS11:
    TA11_E_Import_SecondaryData:
      TaskName: "TA11_E_Import_SecondaryData"
      sourceFile_path: "data/sourceData/secondary"
      dest_db_name: raw


  TA12_DataTransferPrimary:
    TA12_0_DataTransferPrimaryWrapper:
    
    TA12_A_Transfer_DS01:
      taskName: TA12_A_Transfer_DS01
      path_DataRaw: data/rawData/primary/DS01.hdf5
      dest_db_name: raw
      dest_table_name: DS01
      path_gen_manual_col_mapper: app/config/mapper/TA12_DataTransfer/TA12_manualColMapper.yaml
    
    TA12_B_Transfer_DS04:
      taskName: TA12_B_Transfer_DS04
      path_DataRaw: data/rawData/primary/DS04.hdf5
      dest_db_name: raw
      dest_table_name: DS04
      path_gen_manual_col_mapper: app/config/mapper/TA12_DataTransfer/TA12_manualColMapper.yaml
      path_gen_col_rename_mapper: app/config/mapper/TA12_DataTransfer/TA12_DS04_colRenameMapper.yaml

    TA12_C_Transfer_DS07:
      taskName: TA12_C_Transfer_DS07
      path_DataRaw: data/rawData/primary/DS07.hdf5
      dest_db_name: raw
      dest_table_name: DS07
      path_gen_manual_col_mapper: app/config/mapper/TA12_DataTransfer/TA12_manualColMapper.yaml
      path_gen_col_rename_mapper: app/config/mapper/TA12_DataTransfer/TA12_DS07_colRenameMapper.yaml
    
    TA12_D_Transfer_DS11:
      taskName: TA12_D_Transfer_DS11
      path_DataRaw: data/sourceData/primary/DS11/DS11.db
      src_table_name: iwimages
      dest_db_name: raw
      dest_table_name: DS11
      path_gen_manual_col_mapper: app/config/mapper/TA12_DataTransfer/TA12_manualColMapper.yaml
      path_gen_col_rename_mapper: app/config/mapper/TA12_DataTransfer/TA12_DS11_colRenameMapper.yaml
      path_value_mapper: app/config/mapper/TA12_DataTransfer/TA12_valueMapper.yaml

    TA12_E_ConcatPrimaryDataRaw:
      taskName: TA12_E_ConcatPrimaryDataRaw
      src_db_name: raw
      src_table_names: 
        - DS01
        - DS04
        - DS07
        - DS11
      dest_db_name: raw
      dest_table_name: primaryDataRaw
