TA13_A_DataTransfer_DS09:
  rename:
    'No': No_drop
    Botanische Art: species_todo
    Code: IFAW_code
    Herkunft: origin
    Englischer Standardname: engName
    Französicher Standardname: deName
    Deutscher Standardname: frName
    'Unnamed: 7': Unnamed_drop
