# ORM Model: app/utils/SQL/models/raw/orm/PrimaryDataRaw.py

from sqlalchemy import Column, String, Integer, Float, Boolean
from app.utils.SQL.models.OrmBase import OrmBase

class PrimaryDataRaw(OrmBase):
    __tablename__ = "primaryDataRaw"
    
    
    UUID = Column(Integer, primary_key=True, autoincrement=True)
    citeKey = Column(String)
    filename = Column(String)
    sourceNo = Column(String)
    path = Column(String)
    sourceFilePath_rel = Column(String)
    species = Column(String)
    genus = Column(String)
    source_UUID = Column(String)
    filename_drop = Column(String)
    max_split_drop = Column(String)
    specimenID_old = Column(String)
    shotNo = Column(String)
    specimenNo = Column(String)
    pixel_x = Column(Integer)
    pixel_y = Column(Integer)
    family = Column(String)
    GPS_Alt = Column(Float)
    GPS_Lat = Column(Float)
    GPS_Long = Column(Float)
    japName = Column(String)
    specimenNo_old = Column(String)
    order_old = Column(String)
    section_drop = Column(String)
    subgenus_drop = Column(String)
    anatomy1_DS_4 = Column(String)
    anatomy2_DS_4 = Column(String)
    otherNo_drop = Column(String)
    prepNo_drop = Column(String)
    samplingPoint = Column(String)
    subspecies_drop = Column(String)
    individuals_drop = Column(String)
    n_individuals_drop = Column(String)
    view = Column(String)
    lens = Column(Integer)
    microscopicTechnic = Column(String)
    bitDepth = Column(String)
    colorSpace = Column(String)
    colorDepth = Column(String)
    DPI = Column(String)
    totalNumberShots = Column(Integer)
    institution = Column(String)
    contributor = Column(String)
    origin = Column(String)
    digitizedDate = Column(String)
    area_x_mm = Column(Float)
    area_y_mm = Column(Float)
    pixelSize_um_per_pixel = Column(Float)
    numericalAperature_NA = Column(Float)
    sourceStoredLocally = Column(Boolean)
    institutionCode = Column(String)
    sourceFilePath_abs = Column(String)
    woodType = Column(String)
    name_drop = Column(String)
    todo_lens = Column(String)
    filename_old = Column(String)
    source_drop = Column(String)
    todo_bitdepth_old = Column(String)
    engName_old = Column(String)
    version_old = Column(String)
    contributor_old = Column(String)
    institution_old = Column(String)
    view_old = Column(String)
