from sqlalchemy import Column, String, Integer, Float
from app.utils.SQL.models.orm_BaseModel import orm_BaseModel

class WoodTableA(orm_BaseModel):
    __tablename__ = "WoodTableA"

    raw_UUID = Column(String, primary_key=True)
    citeKey = Column(String)
    filename = Column(String)
    sourceNo = Column(String)
    path = Column(String)
    sourceFilePath_rel = Column(String)
    species = Column(String)
    genus = Column(String)
    source_UUID = Column(String)
    shotNo = Column(Float)
    specimenNo = Column(Integer)
    pixel_x = Column(String)
    pixel_y = Column(String)
    family = Column(String)
    GPS_Alt = Column(String)
    GPS_Lat = Column(String)
    GPS_Long = Column(String)
    japName = Column(String)
    samplingPoint = Column(String)
    view = Column(String)
    lens = Column(Float)
    microscopicTechnic = Column(String)
    bitDepth = Column(String)
    colorSpace = Column(String)
    colorDepth = Column(String)
    DPI = Column(String)
    totalNumberShots = Column(String)
    institution = Column(String)
    contributor = Column(String)
    origin = Column(String)
    digitizedDate = Column(String)
    area_x_mm = Column(String)
    area_y_mm = Column(String)
    pixelSize_um_per_pixel = Column(String)
    numericalAperature_NA = Column(String)
    sourceStoredLocally = Column(Float)
    institutionCode = Column(String)
    woodType = Column(String)
    anatomy1_DS04 = Column(String)
    anatomy2_DS04 = Column(String)
    IFAW_code = Column(String)
    engName = Column(String)
    deName = Column(String)
    frName = Column(String)
