from pydantic import BaseModel, ConfigDict
from typing import Optional, List
from sqlalchemy.orm import Session
import logging

from app.utils.SQL.models.api_BaseModel import api_BaseModel

class PrimaryDataRawOut(api_BaseModel):

    UUID: int
    citeKey: Optional[str]
    filename: Optional[str]
    sourceNo: Optional[str]
    path: Optional[str]
    sourceFilePath_rel: Optional[str]
    species: str
    genus: Optional[str]
    source_UUID: Optional[str]
    filename_drop: Optional[str]
    max_split_drop: Optional[str]
    specimenID_old: Optional[str]
    shotNo: Optional[str]
    specimenNo: Optional[str]
    pixel_x: Optional[str]
    pixel_y: Optional[str]
    family: Optional[str]
    GPS_Alt: Optional[str]
    GPS_Lat: Optional[str]
    GPS_Long: Optional[str]
    japName: Optional[str]
    specimenNo_old: Optional[str]
    order_old: Optional[str]
    section_drop: Optional[str]
    subgenus_drop: Optional[str]
    anatomy1_DS_4: Optional[str]
    anatomy2_DS_4: Optional[str]
    otherNo_drop: Optional[str]
    prepNo_drop: Optional[str]
    samplingPoint: Optional[str]
    subspecies_drop: Optional[str]
    individuals_drop: Optional[str]
    n_individuals_drop: Optional[str]
    view: Optional[str]
    lens: Optional[str]
    microscopicTechnic: Optional[str]
    bitDepth: Optional[str]
    colorSpace: Optional[str]
    colorDepth: Optional[str]
    DPI: Optional[str]
    totalNumberShots: Optional[str]
    institution: Optional[str]
    contributor: Optional[str]
    origin: Optional[str]
    digitizedDate: Optional[str]
    area_x_mm: Optional[str]
    area_y_mm: Optional[str]
    pixelSize_um_per_pixel: Optional[str]
    numericalAperature_NA: Optional[str]
    sourceStoredLocally: Optional[str]
    institutionCode: Optional[str]
    sourceFilePath_abs: Optional[str]
    woodType: Optional[str]
    name_drop: Optional[str]
    todo_lens: Optional[str]
    filename_old: Optional[str]
    source_drop: Optional[str]
    todo_bitdepth_old: Optional[str]
    engName_old: Optional[str]
    contributor_old: Optional[str]
    institution_old: Optional[str]
    view_old: Optional[str]
    anatomy1_DS04: Optional[str]
    anatomy2_DS04: Optional[str]
    version_old: Optional[str]

    model_config = ConfigDict(from_attributes=True)

