MM01:
  name: "PCA with binning"

  binning_cfg:
    strategy: "implicit"              # ["none","explicit","implicit"]
    implicit:
      ignore_case: true
      agg_func: "mean"
      patterns:
        geo_shape:  ["area", "roundness", "aspect"]
    explicit: null                    # keep the key so the schema is constant


  dim_reduction:
    method: "linear"
    linear:
      submethod: "PCA"
      PCA:
        n_components: 0.95
        whiten: false
    manifold: null
    encoder: null


