PP01:
  name: "SMOTE Oversampling"
  description: "SMOTE oversampling with a k-neighbors of 3, scope = species"
  resampling:
    method: "SMOTESampler"
    SMOTESampler:
      scope: "species"
      k_neighbors: 3
      sampling_strategy: "auto"
      random_state: 42
    RandomSampler: null
  bootstrapping:
    enabled: true
    n_iterations: 3
    n_samples: 20000

PP02:
  name: "Random Oversampling, hybird, median"
  description: ""
  resampling:
    method: "RandomSampler"
    RandomSampler:
      scope: "genus"
      sampling_strategy: "auto"
      random_state: 42
      mode: "hybrid" # or "over" or "hybrid"
      strategy: "median" # or "mean" or "min" or "max"
  bootstrapping:
    enabled: true
    n_iterations: 3
    n_samples: 1500

PP03:
  name: "Random Oversampling, hybrid, max"
  description: ""
  resampling:
    method: "RandomSampler"
    RandomSampler:
      scope: "family"
      sampling_strategy: "auto"
      random_state: 42
      mode: "hybrid" # or "over" or "hybrid"
      strategy: "max" # or "mean" or "min" or "max"
  bootstrapping:
    enabled: true
    n_iterations: 3
    n_samples: 1500