PP02:
  name: "Random Oversampling"
  description: "Duplicate minority class samples using shotID scope."
  method: "resampling"
  resampling:
    submethod: "oversampling"
    oversampling:
      subsubmethod: "RandomOverSampler"
      RandomOverSampler:
        scope: "species"
        random_state: 42
      SMOTESampler: null
    undersampling: null
    bootstrapping: null
    hybrid: null

PP01:
  name: "SMOTE Oversampling"
  description: "SMOTE interpolation based on shotID labels, using GPU k-NN."
  method: "resampling"
  resampling:
    submethod: "oversampling"
    oversampling:
      subsubmethod: "SMOTESampler"
      SMOTESampler:
        scope: "species"
        k_neighbors: 5
        sampling_strategy: "auto"
        random_state: 42
      RandomOverSampler: null
    undersampling: null
    bootstrapping: null
    hybrid: null